import type { Metadata } from "next";
import { Space_Grotesk, Space_Mono } from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components/app-navbar";
import { Footer } from "@/components/app-footer";
import { SidebarProvider } from "@/components/ui/sidebar";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-sans",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${spaceMono.variable} antialiased dark min-h-screen flex flex-col`}
      >
        <SidebarProvider className="flex flex-col">
          {/* Navbar */}
          <div className="p-8">
            <Navbar />
          </div>

          {/* Page Content */}
          <main className="flex flex-col pb-8">{children}</main>
        </SidebarProvider>
        {/* Footer */}
        <div className="px-8 pb-8">
          <Footer />
        </div>
      </body>
    </html>
  );
}
